version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/bombs
    steps:
      - checkout

      - restore_cache:
          key: bombs-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: bombs-{{ checksum "pom.xml" }}
      
      - run: mvn package
      - run: mkdir artifacts/
      - run: cp target/*.jar artifacts/
      
      - store_artifacts:
          path: artifacts
